Vagrant::Config.run do |config|
    
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "serverprecise32minimal"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box_url = "https://dl.dropbox.com/s/108uhsfwdiy5obc/serverprecise32minimal.box?dl=1"

  # Forward a port from the guest to the host, which allows for outside
  # computers to access the VM, whereas host only networking does not.
  config.vm.forward_port 3000, 3000   # rails
  
  #Customizations
  config.vm.host_name = 'server'
  config.vm.customize ["modifyvm", :id, "--memory", "1024"]
  config.vm.customize ["modifyvm", :id, "--pae", "on"]
  config.vm.share_folder "v-root", "/home/vagrant", "."
  #config.vm.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]

  #Enable provisioning 
  #Comment this lines after installation !
  config.vm.provision :shell, :path => "scripts/setup.sh"
  config.vm.provision :shell, :path => "scripts/provisioners.sh"
  
end
