# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|

  # All Vagrant configuration is done here.
  #For a complete reference, please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "serverprecise32minimal"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box_url = "https://dl.dropbox.com/s/108uhsfwdiy5obc/serverprecise32minimal.box?dl=1"

  #Customizations
  config.vm.host_name = 'server'
  config.vm.customize ["modifyvm", :id, "--memory", "1024"]
  config.vm.customize ["modifyvm", :id, "--pae", "on"]
  config.vm.share_folder "v-root", "/home/vagrant", "."

  #Enable Shell Provisioner
  config.vm.provision :shell, :path => "scripts/setup.sh"
  config.vm.provision :shell, :path => "scripts/provisioners.sh"

  #Enable Chef Provisioner
  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = ["cookbooks"]
      chef.add_recipe "git"
      chef.add_recipe "vim"
      chef.add_recipe "sqlite"
      chef.add_recipe "curl"
  end

end
