Vagrant::Config.run do |config|
    
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "preciseserver32-brightbox"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box_url = ""

  # Forward a port from the guest to the host, which allows for outside
  # computers to access the VM, whereas host only networking does not.
  #config.vm.forward_port 1080, 1080   # mailcatcher
  #config.vm.forward_port 3000, 3000   # rails
  #config.vm.forward_port 3306, 3306   # mysql
  
  #Customizations

  config.vm.host_name = 'server'
  config.vm.customize ["modifyvm", :id, "--memory", "1024"]
  config.vm.share_folder "v-root", "/home/vagrant", "."
  #config.vm.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]
  
end
